[target.x86_64-unknown-linux-gnu]
pre-build = [
    "export PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu=/usr/lib/x86_64-linux-gnu/pkgconfig",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libasound2-dev:$CROSS_DEB_ARCH"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "export PKG_CONFIG_LIBDIR_aarch64_unknown_linux_gnu=/usr/lib/aarch64-linux-gnu/pkgconfig",
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libasound2-dev:$CROSS_DEB_ARCH"
]
